<?php
// load the functions
require_once("includes/functions.php");

?>
<!DOCTYPE html>
<html>

<?php include "includes/head.php";?>
<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
           
			<?php include 'navbar-header.php' ?>
            <!-- /.navbar-top-links -->
			<?php include 'navbar-top-links.php'; ?>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
						<?php include 'includes/run_check.php';?>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Previous Data Summary - run: <?php echo cleanname($_SESSION['focusrun']); ?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
			<ul class="nav nav-pills">
			  <li class="active"><a href="previous_summary.php">Read Summaries</a></li>
			  <li><a href="previous_rates.php">Sequencing Rates</a></li>
			  <li><a href="previous_pores.php">Pore Activity</a></li>
  			  <li><a href="previous_quality.php">Read Quality</a></li>
  			  <li><a href="previous_coverage.php">Coverage Detail</a></li>
			</ul>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><!-- Button trigger modal -->
<button class="btn btn-info" data-toggle="modal" data-target="#modal1">
 <i class="fa fa-info-circle"></i> Reads And Coverage Summary
</button>

<!-- Modal -->
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Reads And Coverage Summary</h4>
      </div>
      <div class="modal-body">
        This panel provides information on the number of reads of each type generated by the metrichor analysis. The avergae read lengths and the maximum read length for each are shown.<br><br>
		Where a reference sequence is available for mapping, the proportion of the reference covered by reads is shown as "Percentage of Reference with Read".<br><br>
		The average depth of sequencing over these positions is shown as "Average Depth Of Sequenced Positions".<br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div></h3>
			  </div>
			  <div class="panel-body">
					<div class="row">
					<div class="col-md-4" id="readnum" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Numbers</div>
					<div class="col-md-4" id="avglen" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Average Length</div>
					<div class="col-md-4" id="maxlen" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Max Length</div>
				</div>
				<div class="row">
					<div class="col-md-6" id="percentcoverage" style="width:50%; height:200px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Reference Coverage</div>
					<div class="col-md-6" id="depthcoverage" style="width:50%; height:200px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Reference Depth</div>
				</div>
			  </div>
			</div>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><!-- Button trigger modal -->
<button class="btn btn-info" data-toggle="modal" data-target="#modal2">
 <i class="fa fa-info-circle"></i> Sequencing Rate Information</h4>
</button>

<!-- Modal -->
<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Sequencing Rate Information
      </div>
      <div class="modal-body">
        Rate of Basecalling<br>
		This plot show the number of reads generated in one minute intervals over the course of the sequencing run.<br><br>
		Average Read Length Over Time<br>
		This plot shows the average length of read generated each minute over the course of the sequncing run.<br><br>
		Average Time To Process Reads Over Time<br>
		This plot shows how long a singel read takes to pass through the pore over the course of the sequencing run (1 minute bins).<br><br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div></h3>
			  </div>
			  <div class="panel-body">
					<div id="readrate" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Rate</div>
					<div id="averagelength" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Length Over Time</div>
					<div id="averagetime" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Time To Complete Reads</div>
			  </div>
			</div>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><!-- Button trigger modal -->
<button class="btn btn-info" data-toggle="modal" data-target="#modal3">
 <i class="fa fa-info-circle"></i> Pore Activity</h4>
</button>

<!-- Modal -->
<div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Pore Activity
      </div>
      <div class="modal-body">
        Active Channels Over Time<br>
		The number of channels actively generating sequence data over the course of the run in 1 minute intervals.<br><br>
		Reads Per Pore<br>
		The number of reads generated by each pore in total over the lifetime of the run.<br><br>
		  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div></h3>
			  </div>
			  <div class="panel-body">
					<div id="activechannels" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x" ></i> Calculating Active Channels Over Time</div>
					<div id="poreproduction" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Pore Productivity</div>
			  </div>
			</div>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><!-- Button trigger modal -->
<button class="btn btn-info" data-toggle="modal" data-target="#modal4">
 <i class="fa fa-info-circle"></i> Quality Information</h4>
</button>

<!-- Modal -->
			<div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel"> Quality Information
			      </div>
			      <div class="modal-body">
			        Read Quality Over Length<br>
					This plot shows the average quality of each position of every read which maps to the reference.<br><br>
			        Read Number Over Length<br>
					This plot shows the numbers of reads at each length which align.<br><br>
					Read Quality For 100 Random Reads<br>
		This plot shows the average quality for 1000 random reads from the run. Note that the 100 reads are not the same for the three classes of read.
		  </div>
					  </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div></h3>
						  </div>
						  <div class="panel-body">
				  			<div id="avgquallength"  style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Quality Scores for Aligned Reads</div>
				  			<div id="numberoverlength"  style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Number of Aligned Reads By Length</div>
				  		  	<div id="allqualities"  style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Quality Scores for 100 Random Reads</div>
				
								  
						</div>
						
						<div class="panel panel-default">
						  <div class="panel-heading">
						    <h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal6">
			 <i class="fa fa-info-circle"></i> Run Summary</h4>
			</button>



<!-- Modal -->
<div class="modal fade" id="modal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Coverage Information
      </div>
      <div class="modal-body">
This series of plots shows xy scatter graphs for coverage against the reference sequence. As well as showing coverage depth, it also reports the positions to which 5' and 3' read ends map.<br><br>
		  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div></h3>
			  </div>
			  <div class="panel-body">
	  			<?php include 'includes/coverageincludes.php';?>  
					  </div>
			</div>
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title"><!-- Button trigger modal -->
<button class="btn btn-info" data-toggle="modal" data-target="#modal6">
 <i class="fa fa-info-circle"></i> Run Summary</h4>
</button>

<!-- Modal -->
<div class="modal fade" id="modal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"> Run Summary
      </div>
      <div class="modal-body">
Key details on the run.<br><br>
		  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div></h3>
			  </div>
			  <div class="panel-body">
	  			<?php prevrunsummary(); ?>
					  </div>
			</div>
			
			
			
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
	
	
    <!-- Core Scripts - Include with every page -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- Page-Level Plugin Scripts - Dashboard -->
			    <script type="text/javascript" src="js/pnotify.custom.min.js"></script>
			    <script type="text/javascript">
				PNotify.prototype.options.styling = "fontawesome";
				</script>
    <script src="js/plugins/morris/raphael-2.1.0.min.js"></script>
    <script src="js/plugins/morris/morris.js"></script>
	
	<!-- Highcharts Addition -->
	<script src="js/highcharts.js"></script>
	<script type="text/javascript" src="js/themes/grid-light.js"></script>
	<script src="http://code.highcharts.com/4.0.3/modules/heatmap.js"></script>
	<script src="http://code.highcharts.com/modules/exporting.js"></script>
	
	
	<script>
	
$(document).ready(function() {
    var options = {
        chart: {
            renderTo: 'readrate',
			zoomType: 'x'
            //type: 'line'
        },
        title: {
          text: 'Rate Of BaseCalling'
        },
		xAxis: {
		            title: {
		                text: 'Time (S)'
		            }
		        },
				yAxis: {
				            title: {
				                text: 'Reads/Minute'
				            }
				        },
						credits: {
						    enabled: false
						  },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: []
    };
	
    $.getJSON('jsonencode/reads_over_time2.php?prev=1&callback=?', function(data) {
		//alert("success");
        options.series = data; // <- just assign the data to the series property.
        
	 
	
        //options.series = JSON2;
		var chart = new Highcharts.Chart(options);
		});
});

	//]]>  

	</script>
	
	<script>
		
	$(document).ready(function() {
	    var options = {
	        chart: {
	            renderTo: 'averagelength',
				zoomType: 'x'
	            //type: 'line'
	        },
	        title: {
	          text: 'Average Read Length Over Time'
	        },
			xAxis: {
			            title: {
			                text: 'Time (S)'
			            }
			        },
					yAxis: {
					            title: {
					                text: 'Average Read Length'
					            }
					        },
							credits: {
							    enabled: false
							  },
	        legend: {
	            layout: 'vertical',
	            align: 'right',
	            verticalAlign: 'middle',
	            borderWidth: 0
	        },
	        series: []
	    };
	
	    $.getJSON('jsonencode/average_length_over_time.php?prev=1&callback=?', function(data) {
			//alert("success");
	        options.series = data; // <- just assign the data to the series property.
	        
		 
		
	        //options.series = JSON2;
			var chart = new Highcharts.Chart(options);
			});
	});

		//]]>  

		</script>

		<script>
		
	$(document).ready(function() {
	    var options = {
	        chart: {
	            renderTo: 'averagetime',
				zoomType: 'x'
	            //type: 'line'
	        },
	        title: {
	          text: 'Average Time to process Reads Over Time'
	        },
			xAxis: {
			            title: {
			                text: 'Time (S)'
			            }
			        },
					yAxis: {
					            title: {
					                text: 'Average Time To Process Read (s)'
					            }
					        },
							credits: {
							    enabled: false
							  },
	        legend: {
	            layout: 'vertical',
	            align: 'right',
	            verticalAlign: 'middle',
	            borderWidth: 0
	        },
	        series: []
	    };
	
	    $.getJSON('jsonencode/average_time_over_time2.php?prev=1&callback=?', function(data) {
			//alert("success");
	        options.series = data; // <- just assign the data to the series property.
	        
		 
		
	        //options.series = JSON2;
			var chart = new Highcharts.Chart(options);
			});
	});

		//]]>  

		</script>
			<script>
		$(document).ready(function() {
		    var options = {
		        chart: {
		            renderTo: 'activechannels',
					zoomType: 'x'
		            //type: 'line'
		        },
		        title: {
		          text: 'Active Channels Over Time'
		        },
				xAxis: {
				            title: {
				                text: 'Time (S)'
				            }
				        },
						yAxis: {
						            title: {
						                text: 'Number of Active Channels'
						            }
						        },
								credits: {
								    enabled: false
								  },
		        legend: {
		            layout: 'vertical',
		            align: 'right',
		            verticalAlign: 'middle',
		            borderWidth: 0
		        },
		        series: []
		    };
	
		    $.getJSON('jsonencode/active_channels_over_time.php?prev=1&callback=?', function(data) {
				//alert("success");
		        options.series = data; // <- just assign the data to the series property.
	        
		 
		
		        //options.series = JSON2;
				var chart = new Highcharts.Chart(options);
				});
		});

			//]]>  

			</script>
 
			<script>
			$(document).ready(function() {
			    var options = {
			        chart: {
						renderTo: 'poreproduction',
			            type: 'heatmap',
			            marginTop: 40,
			            marginBottom: 40
			        },


			        title: {
			            text: 'Reads Per Pore'
			        },

			        xAxis: {
			            title: null,
						labels: {
						    enabled: false
						  },
						
			        },

			        yAxis: {
			            title: null,
						labels: {
						    enabled: false
						  },
						
			        },
					credits: {
					    enabled: false
					  },
			        colorAxis: {
			            min: 0,
			            minColor: '#FFFFFF',
			            maxColor: Highcharts.getOptions().colors[0]
			        },

			        legend: {
			            align: 'right',
			            layout: 'vertical',
			            margin: 0,
			            verticalAlign: 'top',
			            y: 25,
			            symbolHeight: 320
			        },

			        series: []

			    };
			    $.getJSON('jsonencode/readsperpore.php?prev=1&callback=?', function(data) {
					//alert("success");
			        options.series = data; // <- just assign the data to the series property.
	        
		 
		
			        //options.series = JSON2;
					var chart = new Highcharts.Chart(options);
				});
			});
			</script>
				<script>
			$(document).ready(function() {
			    var options = {
			        chart: {
			            renderTo: 'avgquallength',
						zoomType: 'x'
			            //type: 'line'
			        },
			        title: {
			          text: 'Read Quality Over Length For Aligned Reads'
			        },
					xAxis: {
					            title: {
					                text: 'Basepairs'
					            }
					        },
							yAxis: {
							            title: {
							                text: 'Average Quality Score'
							            }
							        },
									credits: {
									    enabled: false
									  },
			        legend: {
			            layout: 'vertical',
			            align: 'right',
			            verticalAlign: 'middle',
			            borderWidth: 0
			        },
			        series: []
			    };
	
			    $.getJSON('jsonencode/readlengthqual.php?prev=1&callback=?', function(data) {
					//alert("success");
			        options.series = data; // <- just assign the data to the series property.
	        
		 
		
			        //options.series = JSON2;
					var chart = new Highcharts.Chart(options);
					});
			});

				//]]>  

				</script>
					<script>
				$(document).ready(function() {
				    var options = {
				        chart: {
				            renderTo: 'allqualities',
							zoomType: 'x'
				            //type: 'line'
				        },
				        title: {
				          text: 'Read Quality For 100 Random Reads'
				        },
						xAxis: {
						            title: {
						                text: 'Basepairs'
						            }
						        },
								yAxis: {
								            title: {
								                text: 'Average Quality Score'
								            }
								        },
										credits: {
										    enabled: false
										  },
				        legend: {
				            layout: 'vertical',
				            align: 'right',
				            verticalAlign: 'middle',
				            borderWidth: 0
				        },
				        series: []
				    };
	
				    $.getJSON('jsonencode/allqualities.php?prev=1&callback=?', function(data) {
						//alert("success");
				        options.series = data; // <- just assign the data to the series property.
	        
		 
		
				        //options.series = JSON2;
						var chart = new Highcharts.Chart(options);
						});
				});

					//]]>  

					</script>
				<script>
		
				$(document).ready(function() {
				    var options = {
				        chart: {
				            renderTo: 'readnum',
							type: 'column'
				            //type: 'line'
				        },
				        title: {
				          text: 'Reads Called'
				        },
						xAxis: {
						            title: {
						                text: 'Strand'
						            }
						        },
								yAxis: {
								            title: {
								                text: 'Number of Reads Called'
								            }
								        },
										credits: {
										    enabled: false
										  },
				        legend: {
				            layout: 'vertical',
				            align: 'right',
				            verticalAlign: 'middle',
				            borderWidth: 0
				        },
				        series: []
				    };
	
				    $.getJSON('jsonencode/readnumber.php?prev=1&callback=?', function(data) {
						//alert("success");
				        options.series = data; // <- just assign the data to the series property.
	        
		 
		
				        //options.series = JSON2;
						var chart = new Highcharts.Chart(options);
						});
				});

					//]]>  

					</script>
					<script>
		
					$(document).ready(function() {
					    var options = {
					        chart: {
					            renderTo: 'avglen',
								type: 'column'
					            //type: 'line'
					        },
					        title: {
					          text: 'Average Read Length'
					        },
							xAxis: {
							            title: {
							                text: 'Strand'
							            }
							        },
									yAxis: {
									            title: {
									                text: 'Average Read Length'
									            }
									        },
											credits: {
											    enabled: false
											  },
					        legend: {
					            layout: 'vertical',
					            align: 'right',
					            verticalAlign: 'middle',
					            borderWidth: 0
					        },
					        series: []
					    };
	
					    $.getJSON('jsonencode/avelen.php?prev=1&callback=?', function(data) {
							//alert("success");
					        options.series = data; // <- just assign the data to the series property.
	        
		 
		
					        //options.series = JSON2;
							var chart = new Highcharts.Chart(options);
							});
					});

						//]]>  

						</script>
					<script>
		
					$(document).ready(function() {
					    var options = {
					        chart: {
					            renderTo: 'maxlen',
								type: 'column'
					            //type: 'line'
					        },
					        title: {
					          text: 'Maximum Read Length'
					        },
							xAxis: {
							            title: {
							                text: 'Strand'
							            }
							        },
									yAxis: {
									            title: {
									                text: 'Maximum Read Length'
									            }
									        },
											credits: {
											    enabled: false
											  },
					        legend: {
					            layout: 'vertical',
					            align: 'right',
					            verticalAlign: 'middle',
					            borderWidth: 0
					        },
					        series: []
					    };
	
					    $.getJSON('jsonencode/maxlen.php?prev=1&callback=?', function(data) {
							//alert("success");
					        options.series = data; // <- just assign the data to the series property.
	        
		 
		
					        //options.series = JSON2;
							var chart = new Highcharts.Chart(options);
							});
					});

						//]]>  

						</script>
						<?php include 'includes/coverageincludesjquery.php';?>
							<script>
		
							$(document).ready(function() {
							    var options = {
							        chart: {
							            renderTo: 'percentcoverage',
										type: 'bar'
							            //type: 'line'
							        },
							        title: {
							          text: 'Percentage of Reference with Read'
							        },
									xAxis: {
									            title: {
									                text: 'Strand'
									            }
									        },
											yAxis: {
											            title: {
											                text: 'Percentage'
											            },
														max: 100
											        },
													credits: {
													    enabled: false
													  },
							        legend: {
							            layout: 'vertical',
							            align: 'right',
							            verticalAlign: 'middle',
							            borderWidth: 0
							        },
							        series: []
							    };
	
							    $.getJSON('jsonencode/percentcoverage.php?prev=1&callback=?', function(data) {
									//alert("success");
							        options.series = data; // <- just assign the data to the series property.
	        
		 
		
							        //options.series = JSON2;
									var chart = new Highcharts.Chart(options);
									});
							});

								//]]>  

								</script>
								<script>
		
								$(document).ready(function() {
								    var options = {
								        chart: {
								            renderTo: 'depthcoverage',
											type: 'bar'
								            //type: 'line'
								        },
								        title: {
								          text: 'Average Depth of Sequenced Positions'
								        },
										xAxis: {
										            title: {
										                text: 'Strand'
										            }
										        },
												yAxis: {
												            title: {
												                text: 'Depth'
												            },
												        },
														credits: {
														    enabled: false
														  },
								        legend: {
								            layout: 'vertical',
								            align: 'right',
								            verticalAlign: 'middle',
								            borderWidth: 0
								        },
								        series: []
								    };
	
								    $.getJSON('jsonencode/depthcoverage.php?prev=1&callback=?', function(data) {
										//alert("success");
								        options.series = data; // <- just assign the data to the series property.
	        
		 
		
								        //options.series = JSON2;
										var chart = new Highcharts.Chart(options);
										});
								});

									//]]>  

									</script>
										<script>
							$(document).ready(function() {
							    var options = {
							        chart: {
							            renderTo: 'numberoverlength',
										zoomType: 'x'
							            //type: 'line'
							        },
							        title: {
							          text: 'Read Number Over Length'
							        },
									xAxis: {
									            title: {
									                text: 'Basepairs'
									            }
									        },
											yAxis: {
											            title: {
											                text: 'Number of Reads of this Length'
											            }
											        },
													credits: {
													    enabled: false
													  },
							        legend: {
							            layout: 'vertical',
							            align: 'right',
							            verticalAlign: 'middle',
							            borderWidth: 0
							        },
							        series: []
							    };
								
								    $.getJSON('jsonencode/readnumberlength.php?prev=1&callback=?', function(data) {
								                //alert("success");
                
								        options.series = data; // <- just assign the data to the series property.
        
								
								        //options.series = JSON2;
								                var chart = new Highcharts.Chart(options);
								        });
							});
						    

								//]]>  

								</script>
    <!-- SB Admin Scripts - Include with every page -->
    <script src="js/sb-admin.js"></script>

    <!-- Page-Level Demo Scripts - Dashboard - Use for reference -->
    <script src="js/demo/dashboard-demo.js"></script>

     <script>
        $( "#infodiv" ).load( "alertcheck.php" ).fadeIn("slow");
        var auto_refresh = setInterval(function ()
            {
            $( "#infodiv" ).load( "alertcheck.php" ).fadeIn("slow");
            //eval(document.getElementById("infodiv").innerHTML);
            }, 10000); // refresh every 5000 milliseconds
    </script>

<?php include "includes/reporting.php";?>
</body>

</html>
