<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal1">
				<i class="fa fa-info-circle"></i> Reads And Coverage Summary
			</button>

			<!-- Modal -->
			<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
							<h4 class="modal-title" id="myModalLabel">Reads And Coverage Summary</h4>
						</div>
						<div class="modal-body">
							This panel provides information on the number of reads of each type generated by the metrichor analysis. The avergae read lengths and the maximum read length for each are shown.<br><br>
							Where a reference sequence is available for mapping, the proportion of the reference covered by reads is shown as "Percentage of Reference with Read".<br><br>
							The average depth of sequencing over these positions is shown as "Average Depth Of Sequenced Positions".<br>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div></h3>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-4" id="readnum" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Numbers</div>
				<div class="col-md-4" id="avglen" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Average Length</div>
				<div class="col-md-4" id="maxlen" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Max Length</div>
			</div>
			<div class="row">
				<div class="col-md-6" id="percentcoverage" style="width:50%; height:200px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Reference Coverage</div>
				<div class="col-md-6" id="depthcoverage" style="width:50%; height:200px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Reference Depth</div>
			</div>
		</div>
	</div>