#!/bin/bash
 
EXPECTED_ARGS=3
E_BADARGS=65
MYSQL=`which mysql`

Q1="CREATE USER '$1'@'localhost' identified by '$2';"
Q2="GRANT ALL ON Gru.* TO '$1'@'localhost';"
Q3="GRANT ALL ON Gru.* TO '$1'@'$3';"
Q4="GRANT ALL ON \`$1\_%\`.* TO '$1'@'localhost';"
Q5="GRANT ALL ON \`$1\_%\`.* TO '$1'@'$3';"
Q6="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}${Q5}${Q6}"
 
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbuser dbpass sourceIP"
  exit $E_BADARGS
fi
 
$MYSQL -uroot -p -e "$SQL"
