<?php
// load the functions
require_once("includes/functions.php");

?>
<!DOCTYPE html>
<html>

<?php include "includes/head.php";?>
<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            
			<?php include 'navbar-header.php' ?>
            <!-- /.navbar-top-links -->
			<?php include 'navbar-top-links.php'; ?>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
						<?php include 'includes/run_check.php';?>
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Current Data Summary - run: <?php echo cleanname($_SESSION['active_run_name']);; ?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                	<?php if (isset($_SESSION['first_visit'])) {}else{?>
					<div class="alert alert-warning alert-dismissible" role="alert">
					  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					  <strong>This page autoupdates.</strong> You do not need to refresh the page. It contains a subset of data available on the data summary page here. Additional data is available once the run is processed and switched to 'previous'.
					</div>
					<?php }; $_SESSION['first_visit']=1;?>
						<div class="panel panel-default">
						  <div class="panel-heading">
						    <h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal1">
			 <i class="fa fa-info-circle"></i> Reads And Coverage Summary
			</button>

			<!-- Modal -->
			<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel">Reads And Coverage Summary</h4>
			      </div>
			      <div class="modal-body">
			        This panel provides information on the number of reads of each type generated by the metrichor analysis. The avergae read lengths and the maximum read length for each are shown.<br><br>
					Where a reference sequence is available for mapping, the proportion of the reference covered by reads is shown as "Percentage of Reference with Read".<br><br>
					The average depth of sequencing over these positions is shown as "Average Depth Of Sequenced Positions".<br>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div></h3>
						  </div>
						  <div class="panel-body">
								<div class="row">
								<div class="col-md-4" id="readnum" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Numbers</div>
								<div class="col-md-4" id="avglen" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Average Length</div>
								<div class="col-md-4" id="maxlen" style="width:33%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Max Length</div>
							</div>
							<div class="row">
								<div class="col-md-6" id="percentcoverage" style="width:50%; height:200px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Reference Coverage</div>
								<div class="col-md-6" id="depthcoverage" style="width:50%; height:200px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Reference Depth</div>
							</div>
						  </div>
						</div>
						<div class="panel panel-default">
						  <div class="panel-heading">
						    <h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal2">
			 <i class="fa fa-info-circle"></i> Sequencing Rate Information</h4>
			</button>

			<!-- Modal -->
			<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel"> Sequencing Rate Information
			      </div>
			      <div class="modal-body">
			        Rate of Basecalling<br>
					This plot show the number of reads generated in one minute intervals over the course of the sequencing run.<br><br>
					Average Read Length Over Time<br>
					This plot shows the average length of read generated each minute over the course of the sequncing run.<br><br>
					Average Time To Process Reads Over Time<br>
					This plot shows how long a singel read takes to pass through the pore over the course of the sequencing run (1 minute bins).<br><br>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div></h3>
						  </div>
						  <div class="panel-body">
								<div id="readrate" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Rate</div>
								<div id="averagelength" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Read Length Over Time</div>
								<div id="averagetime" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Time To Complete Reads</div>
						  </div>
						</div>
						<div class="panel panel-default">
						  <div class="panel-heading">
						    <h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal3">
			 <i class="fa fa-info-circle"></i> Pore Activity</h4>
			</button>

			<!-- Modal -->
			<div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel"> Pore Activity
			      </div>
			      <div class="modal-body">
			        Active Channels Over Time<br>
					The number of channels actively generating sequence data over the course of the run in 1 minute intervals.<br><br>
					Reads Per Pore<br>
					The number of reads generated by each pore in total over the lifetime of the run.<br><br>
					  </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div></h3>
						  </div>
						  <div class="panel-body">
								<div id="activechannels" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x" ></i> Calculating Active Channels Over Time</div>
								<div id="poreproduction" style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Pore Productivity</div>
						  </div>
						</div>
						<div class="panel panel-default">
						  <div class="panel-heading">
						    <h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal4">
			 <i class="fa fa-info-circle"></i> Quality Information</h4>
			</button>

			<!-- Modal -->
			<div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel"> Quality Information
			      </div>
			      <div class="modal-body">
			        Read Quality Over Length<br>
					This plot shows the average quality of each position of every read which maps to the reference.<br><br>
			        Read Number Over Length<br>
					This plot shows the numbers of reads at each length which align.<br><br>
					  </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div></h3>
						  </div>
						  <div class="panel-body">
				  			<div id="avgquallength"  style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Quality Scores for Aligned Reads</div>
				  			<div id="numberoverlength"  style="width:100%; height:400px;"><i class="fa fa-cog fa-spin fa-3x"></i> Calculating Number of Aligned Reads By Length</div>
				  		  	
								  </div>
						</div>
						
						<div class="panel panel-default">
						  <div class="panel-heading">
						    <h3 class="panel-title"><!-- Button trigger modal -->
			<button class="btn btn-info" data-toggle="modal" data-target="#modal6">
			 <i class="fa fa-info-circle"></i> Run Summary</h4>
			</button>

			<!-- Modal -->
			<div class="modal fade" id="modal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="myModalLabel"> Run Summary
			      </div>
			      <div class="modal-body">
			Key details on the run.<br><br>
					  </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			  </div>
			</div></h3>
						  </div>
						  <div class="panel-body">
				  			<?php runsummary(); ?>
								  </div>
						</div>
			
			
			
			                </div>
			                <!-- /.col-lg-12 -->
			            </div>
			        </div>
			        <!-- /#page-wrapper -->

			    </div>
			    <!-- /#wrapper -->
	
	
			    <!-- Core Scripts - Include with every page -->
			    <script src="js/jquery-1.10.2.js"></script>
			    <script src="js/bootstrap.min.js"></script>
			    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>

			    <!-- Page-Level Plugin Scripts - Dashboard -->
			    <script type="text/javascript" src="js/pnotify.custom.min.js"></script>
			    <script type="text/javascript">
				PNotify.prototype.options.styling = "fontawesome";
				</script>
			    <script src="js/plugins/morris/raphael-2.1.0.min.js"></script>
			    <script src="js/plugins/morris/morris.js"></script>
	
				<!-- Highcharts Addition -->
				<script src="http://code.highcharts.com/highcharts.js"></script>
				<script type="text/javascript" src="js/themes/grid-light.js"></script>
				<script src="http://code.highcharts.com/4.0.3/modules/heatmap.js"></script>
				<script src="http://code.highcharts.com/modules/exporting.js"></script>
	
	
				<script>
	
			$(document).ready(function() {
			    var options = {
			        chart: {
			            renderTo: 'readrate',
						zoomType: 'x'
			            //type: 'line'
			        },
					plotOptions: {
					            line: {
					                animation: false
					          
					            }
					        },
			        title: {
			          text: 'Rate Of BaseCalling'
			        },
					xAxis: {
					            title: {
					                text: 'Time (S)'
					            }
					        },
							yAxis: {
							            title: {
							                text: 'Reads/Minute'
							            }
							        },
									credits: {
									    enabled: false
									  },
			        legend: {
			            layout: 'vertical',
			            align: 'right',
			            verticalAlign: 'middle',
			            borderWidth: 0
			        },
			        series: []
			    };
				function loadchirp() {
                
				    $.getJSON('jsonencode/reads_over_time2.php?prev=0&callback=?', function(data) {
				                //alert("success");
                
				        options.series = data; // <- just assign the data to the series property.
        
				                setTimeout(loadchirp,50);
                
				        //options.series = JSON2;
				                var chart = new Highcharts.Chart(options);
				                });
				        }
				        loadchirp();

			});

				//]]>  

				</script>
	
				<script>
		
				$(document).ready(function() {
				    var options = {
				        chart: {
				            renderTo: 'averagelength',
							zoomType: 'x'
				            //type: 'line'
				        },
						plotOptions: {
						            line: {
						                animation: false
						          
						            }
						        },
				        title: {
				          text: 'Average Read Length Over Time'
				        },
						xAxis: {
						            title: {
						                text: 'Time (S)'
						            }
						        },
								yAxis: {
								            title: {
								                text: 'Average Read Length'
								            }
								        },
										credits: {
										    enabled: false
										  },
				        legend: {
				            layout: 'vertical',
				            align: 'right',
				            verticalAlign: 'middle',
				            borderWidth: 0
				        },
				        series: []
				    };
					function loadchirp2() {
                
					    $.getJSON('jsonencode/average_length_over_time.php?prev=0&callback=?', function(data) {
					                //alert("success");
                
					        options.series = data; // <- just assign the data to the series property.
        
					                setTimeout(loadchirp2,50);
                
					        //options.series = JSON2;
					                var chart = new Highcharts.Chart(options);
					                });
					        }
					        loadchirp2();

				});
				   

					//]]>  

					</script>

					<script>
		
				$(document).ready(function() {
				    var options = {
				        chart: {
				            renderTo: 'averagetime',
							zoomType: 'x'
				            //type: 'line'
				        },
						plotOptions: {
						            line: {
						                animation: false
						          
						            }
						        },
				        title: {
				          text: 'Average Time to process Reads Over Time'
				        },
						xAxis: {
						            title: {
						                text: 'Time (S)'
						            }
						        },
								yAxis: {
								            title: {
								                text: 'Average Time To Process Read (s)'
								            }
								        },
										credits: {
										    enabled: false
										  },
				        legend: {
				            layout: 'vertical',
				            align: 'right',
				            verticalAlign: 'middle',
				            borderWidth: 0
				        },
				        series: []
				    };
					function loadchirp3() {
                
					    $.getJSON('jsonencode/average_time_over_time2.php?prev=0&callback=?', function(data) {
					                //alert("success");
                
					        options.series = data; // <- just assign the data to the series property.
        
					        setTimeout(loadchirp3,50);
                
					        //options.series = JSON2;
							var chart = new Highcharts.Chart(options);
				       });
				   }
				   loadchirp3();

				});
				    
					//]]>  

					</script>
						<script>
					$(document).ready(function() {
					    var options = {
					        chart: {
					            renderTo: 'activechannels',
								zoomType: 'x'
					            //type: 'line'
					        },
							plotOptions: {
							            line: {
							                animation: false
							          
							            }
							        },
					        title: {
					          text: 'Active Channels Over Time'
					        },
							xAxis: {
							            title: {
							                text: 'Time (S)'
							            }
							        },
									yAxis: {
									            title: {
									                text: 'Number of Active Channels'
									            }
									        },
											credits: {
											    enabled: false
											  },
					        legend: {
					            layout: 'vertical',
					            align: 'right',
					            verticalAlign: 'middle',
					            borderWidth: 0
					        },
					        series: []
					    };
						function loadchirp4() {
                
						    $.getJSON('jsonencode/active_channels_over_time.php?prev=0&callback=?', function(data) {
						                //alert("success");
                
						        options.series = data; // <- just assign the data to the series property.
        
						                setTimeout(loadchirp4,50);
                
						        //options.series = JSON2;
						                var chart = new Highcharts.Chart(options);
						                });
						        }
						        loadchirp4();

					});
					   

						//]]>  

						</script>
 
						<script>
						$(document).ready(function() {
						    var options = {
						        chart: {
									renderTo: 'poreproduction',
						            type: 'heatmap',
						            marginTop: 40,
						            marginBottom: 40
						        },
								plotOptions: {
								            column: {
								                animation: false
								          
								            }
								        },

						        title: {
						            text: 'Reads Per Pore'
						        },

						        xAxis: {
						            title: null,
									labels: {
									    enabled: false
									  },
						
						        },

						        yAxis: {
						            title: null,
									labels: {
									    enabled: false
									  },
						
						        },
								credits: {
								    enabled: false
								  },
						        colorAxis: {
						            min: 0,
						            minColor: '#FFFFFF',
						            maxColor: Highcharts.getOptions().colors[0]
						        },

						        legend: {
						            align: 'right',
						            layout: 'vertical',
						            margin: 0,
						            verticalAlign: 'top',
						            y: 25,
						            symbolHeight: 320
						        },

						        series: []

						    };
							function loadchirp5() {
                
							    $.getJSON('jsonencode/readsperpore.php?prev=0&callback=?', function(data) {
							                //alert("success");
                
							        options.series = data; // <- just assign the data to the series property.
        
							                setTimeout(loadchirp5,50);
                
							        //options.series = JSON2;
							                var chart = new Highcharts.Chart(options);
							                });
							        }
							        loadchirp5();

						});
						  
						</script>
							<script>
						$(document).ready(function() {
						    var options = {
						        chart: {
						            renderTo: 'avgquallength',
									zoomType: 'x'
						            //type: 'line'
						        },
								plotOptions: {
								            line: {
								                animation: false
								          
								            }
								        },
						        title: {
						          text: 'Read Quality Over Length of Aligned Reads'
						        },
								xAxis: {
								            title: {
								                text: 'Basepairs'
								            }
								        },
										yAxis: {
										            title: {
										                text: 'Average Quality Score'
										            }
										        },
												credits: {
												    enabled: false
												  },
						        legend: {
						            layout: 'vertical',
						            align: 'right',
						            verticalAlign: 'middle',
						            borderWidth: 0
						        },
						        series: []
						    };
							function loadchirp6() {
                
							    $.getJSON('jsonencode/readlengthqual.php?prev=0&callback=?', function(data) {
							                //alert("success");
                
							        options.series = data; // <- just assign the data to the series property.
        
							                setTimeout(loadchirp6,50);
                
							        //options.series = JSON2;
							                var chart = new Highcharts.Chart(options);
							                });
							        }
							        loadchirp6();

						});
						    

							//]]>  

							</script>
								<script>
							$(document).ready(function() {
							    var options = {
							        chart: {
							            renderTo: 'numberoverlength',
										zoomType: 'x'
							            //type: 'line'
							        },
									plotOptions: {
									            line: {
									                animation: false
									          
									            }
									        },
							        title: {
							          text: 'Read Number Over Length'
							        },
									xAxis: {
									            title: {
									                text: 'Basepairs'
									            }
									        },
											yAxis: {
											            title: {
											                text: 'Number of Reads of this Length'
											            }
											        },
													credits: {
													    enabled: false
													  },
							        legend: {
							            layout: 'vertical',
							            align: 'right',
							            verticalAlign: 'middle',
							            borderWidth: 0
							        },
							        series: []
							    };
								function loadchirp12() {
                
								    $.getJSON('jsonencode/readnumberlength.php?prev=0&callback=?', function(data) {
								                //alert("success");
                
								        options.series = data; // <- just assign the data to the series property.
        
								                setTimeout(loadchirp12,50);
                
								        //options.series = JSON2;
								                var chart = new Highcharts.Chart(options);
								                });
								        }
								        loadchirp12();

							});
						    

								//]]>  

								</script>
							<script>
		
							$(document).ready(function() {
							    var options = {
							        chart: {
							            renderTo: 'readnum',
										type: 'column'
							            //type: 'line'
							        },
									plotOptions: {
									            column: {
									                animation: false
									          
									            }
									        },
							        title: {
							          text: 'Reads Called'
							        },
									xAxis: {
									            title: {
									                text: 'Strand'
									            }
									        },
											yAxis: {
											            title: {
											                text: 'Number of Reads Called'
											            }
											        },
													credits: {
													    enabled: false
													  },
							        legend: {
							            layout: 'vertical',
							            align: 'right',
							            verticalAlign: 'middle',
							            borderWidth: 0
							        },
							        series: []
							    };
								function loadchirp7() {
                
								    $.getJSON('jsonencode/readnumber.php?prev=0&callback=?', function(data) {
								                //alert("success");
                
								        options.series = data; // <- just assign the data to the series property.
        
								                setTimeout(loadchirp7,50);
                
								        //options.series = JSON2;
								                var chart = new Highcharts.Chart(options);
								                });
								        }
								        loadchirp7();

							});
						    
							    

								//]]>  

								</script>
								<script>
		
								$(document).ready(function() {
								    var options = {
								        chart: {
								            renderTo: 'avglen',
											type: 'column'
								            //type: 'line'
								        },
										plotOptions: {
										            column: {
										                animation: false
										          
										            }
										        },
								        title: {
								          text: 'Average Read Length'
								        },
										xAxis: {
										            title: {
										                text: 'Strand'
										            }
										        },
												yAxis: {
												            title: {
												                text: 'Average Read Length'
												            }
												        },
														credits: {
														    enabled: false
														  },
								        legend: {
								            layout: 'vertical',
								            align: 'right',
								            verticalAlign: 'middle',
								            borderWidth: 0
								        },
								        series: []
								    };
									function loadchirp8() {
                
									    $.getJSON('jsonencode/avelen.php?prev=0&callback=?', function(data) {
									                //alert("success");
                
									        options.series = data; // <- just assign the data to the series property.
        
									                setTimeout(loadchirp8,50);
                
									        //options.series = JSON2;
									                var chart = new Highcharts.Chart(options);
									                });
									        }
									        loadchirp8();

								});
								      

									</script>
								<script>
		
								$(document).ready(function() {
								    var options = {
								        chart: {
								            renderTo: 'maxlen',
											type: 'column'
								            //type: 'line'
								        },
										plotOptions: {
										            column: {
										                animation: false
										          
										            }
										        },
								        title: {
								          text: 'Maximum Read Length'
								        },
										xAxis: {
										            title: {
										                text: 'Strand'
										            }
										        },
												yAxis: {
												            title: {
												                text: 'Maximum Read Length'
												            }
												        },
														credits: {
														    enabled: false
														  },
								        legend: {
								            layout: 'vertical',
								            align: 'right',
								            verticalAlign: 'middle',
								            borderWidth: 0
								        },
								        series: []
								    };
									function loadchirp9() {
                
									    $.getJSON('jsonencode/maxlen.php?prev=0&callback=?', function(data) {
									                //alert("success");
                
									        options.series = data; // <- just assign the data to the series property.
        
									                setTimeout(loadchirp9,50);
                
									        //options.series = JSON2;
									                var chart = new Highcharts.Chart(options);
									                });
									        }
									        loadchirp9();

								});
								   

									//]]>  

									</script>
									
										<script>
		
										$(document).ready(function() {
										    var options = {
										        chart: {
										            renderTo: 'percentcoverage',
													type: 'bar'
										            //type: 'line'
										        },
												plotOptions: {
												            bar: {
												                animation: false
												          
												            }
												        },
										        title: {
										          text: 'Percentage of Reference with Read'
										        },
												xAxis: {
												            title: {
												                text: 'Strand'
												            }
												        },
														yAxis: {
														            title: {
														                text: 'Percentage'
														            },
																	max: 100
														        },
																credits: {
																    enabled: false
																  },
										        legend: {
										            layout: 'vertical',
										            align: 'right',
										            verticalAlign: 'middle',
										            borderWidth: 0
										        },
										        series: []
										    };
											function loadchirp10() {
                
											    $.getJSON('jsonencode/percentcoverage.php?prev=0&callback=?', function(data) {
											                //alert("success");
                
											        options.series = data; // <- just assign the data to the series property.
        
											                setTimeout(loadchirp10,50);
                
											        //options.series = JSON2;
											                var chart = new Highcharts.Chart(options);
											                });
											        }
											        loadchirp10();

										});
										   

											//]]>  

											</script>
											<script>
		
											$(document).ready(function() {
											    var options = {
											        chart: {
											            renderTo: 'depthcoverage',
														type: 'bar'
											            //type: 'line'
											        },
													plotOptions: {
													            bar: {
													                animation: false
													          
													            }
													        },
											        title: {
											          text: 'Average Depth of Sequenced Positions'
											        },
													xAxis: {
													            title: {
													                text: 'Strand'
													            }
													        },
															yAxis: {
															            title: {
															                text: 'Depth'
															            },
															        },
																	credits: {
																	    enabled: false
																	  },
											        legend: {
											            layout: 'vertical',
											            align: 'right',
											            verticalAlign: 'middle',
											            borderWidth: 0
											        },
											        series: []
											    };
												function loadchirp11() {
                
												    $.getJSON('jsonencode/depthcoverage.php?prev=0&callback=?', function(data) {
												                //alert("success");
                
												        options.series = data; // <- just assign the data to the series property.
        
												                setTimeout(loadchirp11,50);
                
												        //options.series = JSON2;
												                var chart = new Highcharts.Chart(options);
												                });
												        }
												        loadchirp11();

											});
											
												//]]>  

												</script>
			    <!-- SB Admin Scripts - Include with every page -->
			    <script src="js/sb-admin.js"></script>

			    <!-- Page-Level Demo Scripts - Dashboard - Use for reference -->
			    <script src="js/demo/dashboard-demo.js"></script>

     <script>
        $( "#infodiv" ).load( "alertcheck.php" ).fadeIn("slow");
        var auto_refresh = setInterval(function ()
            {
            $( "#infodiv" ).load( "alertcheck.php" ).fadeIn("slow");
            //eval(document.getElementById("infodiv").innerHTML);
            }, 10000); // refresh every 5000 milliseconds
    </script>

			<?php include "includes/reporting.php";?>
</body>

			</html>
 			