#!/bin/bash
 
EXPECTED_ARGS=3
E_BADARGS=65
MYSQL=`which mysql`

Q1="CREATE USER '$1'@'localhost' identified by '$2';"
Q2="CREATE DATABASE Gru;"
Q3="GRANT ALL ON *.* TO '$1'@'$3' identified by '$2';"
Q6="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q6}"
 
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbuser dbpass sourceIP"
  exit $E_BADARGS
fi
 
$MYSQL -uroot -p -e "$SQL"
$MYSQL -uroot -p Gru < Gru0.7.sql
